version "3.2.5"
#include "HacxReplacers.zc"

// ------------------------------------------------------------------------------------------------
//
//   NC HUD - Hacx
//
// ------------------------------------------------------------------------------------------------

class NCH_HacxStatusBar : NCH_BaseHUD
{
}

class MO_WeakArmor : MO_LightArmor
{
	Default
	{
	  Tag "$TAG_WEAKARM";
	  Armor.SaveAmount 50;
	}

	States
	  {
	  Spawn:
		4RM1 A -1;
		Stop;
	  }
}